import type { ReactElement } from 'react';
import type { NextPageWithLayout } from './_app';

import Head from 'next/head';

import Layout from '../components/Layout';

const Page: NextPageWithLayout = () => {
  return (
    <Head>
      <title>Boards</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Page;